language: node_js
node_js:
- node
addons:
  sauce_connect: true
env:
  global:
    - SAUCE_USERNAME=forabi
    - secure: OxeH2TFcIdfHZuBJR2KR/cNJKhpd9CTs5bj0azLbu/Rr1SfBIpFXmRWPI9Zn7tFKTTfZvfGBXg6TInWzgPtovdX0IFIxU2G6K2ApfF6THW2kM8vnWll4pOXAQg614qLcfxMPehhoAyd0h7z5FilU6j5NiOga6C5UKLYLX3i3LcBnRD5OHoWKGkqYnrxTWeLzlDmJsJr5BHapUZfuo5v8yHuUbkyQ5duTCkx08HzwkrJfsvkFKN5D62PQLZGUN537C3PIi6WcsXoenRi57KL3U7tQ/OdAavYV5OFiY4UicOj2fhDV38UpFQbXnNv8d1YSe0j26WzEPBwU9hsANnLAE07TpcKUGePBf2KiIwJnRGuXFBdpGJ+FBCybkF0J+cF/2kEHwkadeHdGdg6+LVtQcxG7bsA2CmpVng58NHOL2WoO19rTb7o3zgzJGc6tR5gLinHoqdvNWGJLI9Q9F9gdHRSvj+kNOzvvlHO0YzWbrJjAlYU+/2D4bU4EZgonCe8ivOaO6lf6jEZtY4gLDUyJ6lZbW+n/XCOEK3ygHQS57Rq0PEMeDzEqElLpFOF6hTow0sZp6MrtaFkw1dlzKU2mzZhsTPE2/nfcZSHucjQesumBTxoM6zzh4nIKuNrAOhQ/Uq4b1gtd+b7xfYxMW6LwgcmZctj8vSsbOTYAa0fdU3M=
